services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  rinha2025-backend:
    build:
      context: .
      dockerfile: Rinha2025.Backend/Dockerfile
    container_name: rinha2025-backend
    depends_on:
      - rabbitmq
    environment:
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__Queue=payments
      - ASPNETCORE_URLS=http://0.0.0.0:9999
    ports:
      - "9999:9999"
    networks:
      - backend

networks:
  backend:
    driver: bridge